package qin.javaee8.hibernate.tools;

/**
 * oppo手机名称
 */
public interface OppoGoodsNames
{
    String[] oppoNames = new String[]{
            " 美美爱四季高雅沙发垫布艺秋季时尚防滑坐垫简洁沙发巾欧式沙发",
            "奥丝布莱特中老年女式羊绒衫大码妈妈装加厚打底毛衣针织衫宽松保",
            " vivo X9 全网通 4GB+64GB 移动联通电信4G手机 双卡双待X9i星空",
            " OPPO R9s Plus 全网通4G手机 双卡双待 黑色 全网通(6G RAM+64GR",
            " OPPO R9s Plus 全网通4G手机 双卡双待 玫瑰金 全网通(6GRAM+64G",
            " OPPO R9s 全网通4G手机 双卡双待 黑色 全网通(4G RAM+64GROM)标",
            " OPPO R9s 全网通4G手机 双卡双待 玫瑰金 全网通(4G RAM+64GROM)",
            " OPPO A59s 全网通4G手机 双卡双待 玫瑰金 全网通(4G RAM +32GRO",
            " OPPO A57 全网通4G手机 双卡双待 金色 全网通(3G RAM+32GROM)标",
            " OPPO A57 全网通4G手机 双卡双待 玫瑰金 全网通(3G RAM+32GROM)",
            " OPPO A37 全网通4G手机 双卡双待 玫瑰金 全网通(2G RAM+16GROM)",
            " OPPO R9s Plus 全网通4G手机 双卡双待 黑色 全网通(6G RAM+64GR",
            " OPPO A57 全网通双卡双待4G指纹识别智能手机 3GB+32GB内存版5.2",
            " OPPO A59S 全网通4G智能手机 5.5大屏双卡双待手机4GB+32GB内存",
            " OPPO R9s 全网通双卡双待4G指纹识别智能手机 5.5大屏手机4G运存",
            "OPPO R9s Plus全网通4G 双卡双待智能手机 6.0大屏 6GB+64GB 金色",
            " 罗马仕（ROMOSS）sense6 加量版超智能 移动电源/充电宝20000毫",
            "中兴（ZTE）L580 老人手机  移动/联通2G 黑色",
            " 罗马仕（ROMOSS）sense6Plus 移动电源/充电宝 20000毫安苹果/安",
            " 乐心 mambo 智能手环 来电提醒 来电显示 睡眠监测 计步 防水专",
            " 联想 ZUK手机（z1221）白色 64GB 移动联通电信4G手机双卡双待4G",
            " 小米（MI）智能手环1代 普通版 小米手环 防水腕带 睡眠识别睡眠",
            "OPPO A33 2GB+16GB内存版 白色 移动4G手机",
            " 金士顿（Kingston）32GB 80MB/s TF(Micro SD)Class10UHS-I高速",
            "华为 畅享5S 金色 移动联通电信4G手机 双卡双待",
            " 三星 Galaxy S7 edge（G9350）4GB+32GB版铂光金移动联通电信4G",
            "三星 Galaxy A9 (SM-A9100) 魔幻金 全网通4G手机 双卡双待",
            " 魅族 魅蓝note3 全网通公开版 16GB 银色 移动联通电信4G手机双",
            "OPPO A37 2GB+16GB内存版 玫瑰金 全网通4G手机 双卡双待",
            " 摩托罗拉 Moto Z 模块化手机 流金黑 全网通4G手机 双卡双待",
            "Apple iPhone 7 Plus (A1661) 128G 玫瑰金色 移动联通电信4G手机",
            " 荣耀 畅玩5C 全网通 高配版 3GB+32GB 落日金移动联通电信4G手机",
            "金立M6 摩卡金 4GB+128GB版 移动联通电信4G手机 双卡双待",
            "【移动购机赠费】OPPO R9s 全网通4G 64G 双卡双待手机 玫瑰金",
            " 荣耀 畅玩6X 4GB 32GB 全网通4G手机 高配版 铂光金",
            "【北京移动购机赠费】OPPO R9s 全网通4G 64G 双卡双待手机 黑色",
            "OPPO R9s 全网通4G+64G 双卡双待手机 玫瑰金",
            "OPPO R9s 全网通4G+64G 双卡双待手机 黑色",
            "OPPO A59s 4GB+32GB内存版 玫瑰金 全网通4G手机 双卡双待",
            "【天津移动购机赠费】OPPO R9s 玫瑰金 全网通4G手机 双卡双待",
            "OPPO A57 3GB+32GB内存版 玫瑰金 全网通4G手机 双卡双待",
            " OPPO R9s 全网通4GB+64GB 双卡双待手机 黑色",
            " OPPO R9s 全网通4GB+64GB 双卡双待手机 黑色",
            " OPPO R9s Plus 6GB 64GB内存版 全网通4G手机 双卡双待 玫瑰金",
            " OPPO R9s Plus 6GB+64GB内存版 全网通4G手机 双卡双待 玫瑰金",
            " OPPO R9s Plus 6GB+64GB内存版 全网通4G手机 双卡双待 玫瑰金",
            "【电信赠费版】OPPO R9s 全网通4G+64G 双卡双待手机 玫瑰金",
            "OPPO R9s Plus 6GB+64GB内存版 全网通4G手机 双卡双待 黑色",
            " 富士（FUJIFILM）INSTAX 一次成像相机MINI相纸（胶片）白边（双",
            " 三星（SAMSUNG）32GB UHS-1 Class10 TF(MicroSD)存储卡（读速48",
            " BIAZE 苹果6/5s数据线 手机充电器线电源线 1.2米 白色支持iphon",
            "联想(Lenovo) MA388 老人手机 星夜黑 移动联通2G手机 双卡双待",
            "南孚(NANFU)LR6AA聚能环5号碱性电池干电池12粒挂卡装/儿童玩具/",
            "OPPO R801T 翻盖超薄音乐时尚OPPO u521手机",
            "小米正品Xiaomi/小米 红米手机2增强版双卡双待智能安卓手机包邮",
            "现货当天发送豪礼 Xiaomi/小米 红米手机3S全网通红米3s手机",
            "分期免息送豪礼OPPO R9全网通手机oppor9 r9plus oppor9手机r9s",
            "分期免息OPPO R9S全网通正品手机oppor9plus oppor9s手机oppor9s",
            "分期购OPPO A37m手机oppoa37 oppo r9s plus oppor9 A37 A57 s",
            "【分期免息】送豪礼OPPO R9S全网通正品手机oppor9plus oppor9s红",
            "OPPO A93黑白魔方直板按键音乐时尚手机 oppoa93男女学生款手机",
            "【新品】OPPO R9S全网通前置1600万像素拍照手机分期免息oppor9s",
            "OPPO X9000/U525手机正品行货翻盖老年人手机女款oppou525包邮",
            "正常发货◆OPPO R9S正品手机 oppor9s oppor9s手机r9splus r9plus",
            "6期免息送碎屏险 OPPO R9S新品手机oppor9s r9splus oppor9s手机",
            "正常发货抢豪礼OPPO R9S正品手机oppor9splus oppor9s oppor 9s",
            "正常发货送豪礼OPPO R9S智能手机oppor9s  r9splus oppor9s手机",
            "分期免息送豪礼OPPO R9S正品手机oppor9s r9splus oppor9s手机r9",
            "分期免息抢豪礼OPPO R9S正品智能手机oppo r9splus oppor9s新年红",
            "6期免息 OPPO R9S 全网通4+64G内存 oppor9s手机 R9Splus",
            "当天发货 分期免息OPPO R9S全网通智能手机oppor9s oppo r9s",
            "分期免息OPPO R9S正品 oppor9s oppor9s手机 oppor9plus r9splus",
            "[开年大促]OPPO R9S全网通智能4G手机正品oppor9s r9plus r9splus",
            "OPPO R9S全网通4G手机oppor9 oppor9s手机r9splus r9plus分期免息",
            "12期免息OPPO R9S手机全网通黑oppor9splus oppor9s手机 oppor9s",
            "12期免息 OPPO R9S手机全网通黑r9s oppor9splus r9 oppor9s",
            "12期免息 OPPO R9S正品 oppor9s oppor9s手机 r9splus oppor9 r9s",
            "分期免息 OPPO R9S 全网通智能4G拍照手机 正品oppor9splus红色版",
            "实体现货OPPO A33高颜值双流光镜面拍照4G移动手机oppoa33包顺丰",
            "12期免息OPPO R9S 4G智能拍照手机oppor9s oppor9S正品全网通指纹",
            "天天特价12期免息 OPPO R9S新年红oppor9s正品手机 r9splus手机r9",
            "OPPO 1107智能遥控移动4G双卡双待安卓手机四核超薄智能遥控手机",
            "OPPO R7007/R3 新款超薄移动4G智能手机OPPOR3四核5寸正品",
            "OPPO A31 16G流光镜面双卡移动4G音乐智能手机拍照原装正品包邮",
            "分期免息OPPO A57正品智能oppoa57手机 oppoa59s r9s a57手机 r7s",
            "6期免息OPPO A57全网通手机oppoa57 oppo a57 oppor9s r9手机",
            "【正常发货】OPPO A57全网通手机 oppoa59s oppoa59m oppor9s a57",
            "OPPO R9S手机全网通正品行货黑色玫瑰金4g+64G指纹oppor9美颜包邮",
            "6期免息OPPO A57全网通正品手机oppoa57 oppoa37 oppoa59s r9s",
            "OPPO A57 12期免息 新款智能手机 正品 oppoa33 a59 oppo a57",
            "OPPO A57 12期免息 新款手机oppoa57手机 oppoa59 a59 oppoa33 a5",
            "OPPO A57手机oppoa57手机正品全网通全新a57oppo oppoa37m a59s",
            "OPPO A33 全网通双卡4G智能美颜自拍手机正品行货全新机全国联保",
            "【分期免息】送豪礼OPPO R9S手机全网通黑r9plus r9 oppor9s红",
            "OPPO R9S手机 黑色全网通正品行货4g+64G指纹识别oppor9美颜包邮",
            "全新正品 OPPO R7S 全网通移动联通电信4G大屏5.5寸智能手机",
            "OPPO R9S 4G全网通R9S正品智能手机oppor9s 正品全网通指纹解锁",
            "OPPO A33全网通oppo a33移动版四核智能双卡双待4G拍照手机包邮",
            "顺丰包邮OPPO R7S 全网通4G手机oppoR7S移动4G oppor9 4G+64G手机",
            "包邮OPPO R7007/R3新款超薄移动4G智能手机OPPOR3四核5寸正品行货",
            "OPPOA33双卡双待移动4G5英寸智能音乐双流光镜面拍照手机正品包邮",
            "OPPO N3 N5207 电动旋转摄像头 移动4G 手机OPPON3 N5209 包邮",
            "OPPO R8207 R1C原装正品超薄智能音乐美颜手机",
            "OPPO A31T高清拍照流光镜面智能四核双卡移动女士4G手机全国包邮",
            "【实体保障】OPPO A57 行货正品智能手机oppoa57 oppoa33 oppoa37",
            "OPPO A33全网通智能手机 oppoa33m 顺风包邮oppoa37全国联保",
            "OPPO A31T 高清拍照流光镜面智能四核双卡移动女士4G手机全国包邮",
            "OPPO N5207 N3 电动旋转摄像头 移动4G 手机OPPON3 N5207 包邮",
            "OPPO R9s 新年特别版红色正品闪充1600万拍照大屏智能手机oppor9s",
            "OPPO A57全网通手机oppoa59 OPPOA59S双卡双待oppoa57OPPOA57手机",
            " MUNU/木木 三合一充电线 苹果数据线 安卓数据线 苹果充电线ipho",
            " 魅爱琳 Mei Ailin OPPO R9S手机套 浮雕卡通 r9s手机壳外壳保护",
            " 魅爱琳 Mei Ailin OPPO R9s手机套 磨砂硬壳 R9s plus手机壳保护",
            " MUNU/木木 MicroUSB数据线 小米 华为 三星 索尼 联想 酷派 OPPO",
            " EPAI/艺派 小米5金属活塞耳机 OPPO R7plus 荣耀V8 mate8 X7plus",
            " MUNU/木木 运动臂带 跑步臂带 包 运动手机臂带 苹果 三星 华为",
            " SAMSUNG三星 三星S4内存卡 32G正品 tf卡 SD卡 note2 I9300 S5i9",
            " 美壳壳 oppo A520 A125 A127 A201 A203 A115 A100手机原装电池B",
            " 魅爱琳 Mei Ailin R9s手机套 商务电镀皮防摔硅胶 软套保护壳外",
            " 美壳壳 OPPO R831T电池 OPPOR831T手机原装电板 R2017R829T原装",
            " 美壳壳 oppo R821T R820 R815T R833T手机电池 BLT029 原装 正品",
            " 美壳壳 OPPO充电器原装正品Find5 X909T X907 N1T R819TR815t手",
            "KONEL 透明TPU软壳全屏后壳高清透薄 适于oppo R7s手机壳",
            "KONEL 钢化膜手机保护膜 适用于OPPOR7plus R7plus手机钢化膜",
            " KONEL 手机钢化膜玻璃膜高清贴膜保护膜 适用于OPPO R7S钢化膜r7",
            " KONEL oppo R9手机壳 R9 plus保护套皮质电镀软外壳硅胶适用于op",
            " 魅爱琳 Mei Ailin OPPOR9s手机壳 真皮皮套 OPPO R9splus手机套",
            " KONEL R7plus手机壳保护套TPU软套防摔透明 适于OPPOR7PLUS手机",
            " 美壳壳 OPPO R5钢化玻璃膜 R5手机贴膜 oppor5防爆膜r5高清保护",
            " MUNU/木木 OPPO R9 R9s R9plus R9splus A59 R7plus R7s A53 A57",
            " 魅爱琳 Mei Ailin oppo R9手机壳 户外防摔 OPPOR9plus手机套保",
            " 魅爱琳 Mei Ailin oppoR9手机套 浮雕可爱卡通 r9plus手机壳外壳",
            " 艾斯盾 苹果 安卓 二合一手机数据线usb充电线 苹果7 三星 小米",
            " 艾斯盾 小迷你蓝牙耳机4.0 无线微型隐形耳塞式蓝牙运动跑步立体",
            " 艾斯盾 苹果7充电宝 大毫安轻薄聚合物充电宝手机太阳能移动电源",
            " MUNU/木木 蓝牙运动耳机 跑步蓝牙耳机 防脱落 运动蓝牙耳机耳挂",
            "艾斯盾 OPPO A33钢化膜oppoa33w手机玻璃膜高清A33T保护贴膜",
            " 艾斯盾 OPPOA51钢化玻璃膜 oppo a51T手机贴膜 a51t保护膜高清膜",
            " 滚石stne OPPO R9plus钢化膜 钢化膜玻璃膜 r9plus手机保护贴膜",
            " 滚石stne OPPO R7S钢化膜 钢化玻璃膜OPPOR7S手机防爆膜OPPOR7sm",
            " SmallGray 充电宝加量版 20000mAh oppovivo超智能移动电源充电",
            " 诺雅尚品 创意迷你手机卡通风扇苹果安卓充电宝USB静音便携小风",
            "艾克司（Acase）手机保护套通用款黑色翻盖皮套全包附挂绳适用苹",
            "艾克司（Acase）手机保护套通用款粉色翻盖附挂绳适用苹果iphone7",
            " MUNU/木木 蓝牙耳机 商务蓝牙耳机 通用音乐无线蓝牙耳机耳塞式",
            " ROCK洛克 安卓手机通用自拍杆后视镜迷你神器oppo苹果6Svivo华为",
            " 哈马 鹰爪自行车手机支架通用山地车电动车摩托导航手机架骑行装",
            " HUAWEI AM04S 蓝牙耳机 通用无线音乐商务降噪 华为 mate9mate9p",
            " MUNU/木木 苹果安卓通用耳机 入耳式线控带麦 华为 小米 三星OPP",
            " 哈马(HIPPO) OPPO R9 Plus 全屏幕覆盖钢化玻璃膜 全屏钢化膜手",
            " 哈马(HIPPO) OPPO R9 Plus 全屏幕覆盖钢化玻璃膜 全屏钢化膜手",
            " 克研纤薄防摔-里层光学纹设计 OPPO R9 plus 纤薄手机壳保护套防",
            " 克研纤薄防摔-里层光学纹设计 OPPO R9 plus 纤薄手机壳保护套防",
            " 黑鱼 oppor7s手机壳oppor7s保护套硅胶男女款r7sm可爱防摔卡通樱",
            " 黑鱼 手机壳套oppor7plus男女款软硅胶防摔韩卡通我累了官方标配",
            "艾斯盾 BLP587手机电池 适用于OPPO R8205 R1C R8207",
            " 魅爱琳 Mei Ailin oppo R9手机壳 卡通皮套 R9plus手机套保护套",
            " MUNU/木木 OPPO R9 R9tm 手机壳 手机套 保护壳 保护套 浮雕壳彩",
            " 魅爱琳 Mei Ailin 第三代迷你线控折叠自拍杆/拍照自拍神器适用",
            " 魅爱琳 Mei Ailin OPPO R9s手机套 透明软套 OPPOR9s plus手机壳",
            "艾克司（Acase）手机钢化玻璃全屏覆盖屏幕保护贴膜金色适用于OPP",
            "艾克司（Acase）手机壳透明硅胶防摔全包保护套TPU软壳适用于OPPO",
            "艾克司（Acase）手机钢化玻璃全屏覆盖屏幕保护贴膜白色适用于OPP",
            " povov 手机双USB车载充电器一拖二车充华为苹果三星OPPOVIVO小米",
            " KONEL OPPO R9s手机壳保护套手机皮套免翻盖开窗支架 适于OPPOR9",
            " 艾斯盾 手机数据线USB彩色安卓充电器 22CM 1米适用于三星/小米/",
            " Pisen/品胜 爱车充 苹果iphone6 7 6s PLUS iphone5s/5c车载充电",
            " Pisen/品胜 安卓Micro USB充电数据线 II代 1.5米 通用数据线适",
            " Pisen/品胜 Micro USB 安卓数据线 MOT-2 适用小米 华为 VIVOOPP"
    };
}
